[package]
name = "karplus-strong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp_signal = "*"
dasp_ring_buffer = "*"
dasp_sample = "*"
hound = "*"
